dynaconf_merge = true

[rag]
name = "pai_rag"
version = "0.1.1"

[rag.agent]
type = "react"

[rag.agent.custom_config]
agent_file_path = ""

[rag.agent.intent_detection]
type = ""

[rag.agent.tool]
type = "" # [built-in", "python", "api"]

[rag.chat_engine]
type = "CondenseQuestionChatEngine"

[rag.chat_store]
type = "Local" # [Local, Aliyun-Redis]
host = "Aliyun-Redis host"
password = "Aliyun-Redis user:pwd"
persist_path = "localdata/storage"

[rag.data_analysis]
analysis_type = "nl2pandas"
nl2sql_prompt = "给定一个输入问题，创建一个语法正确的{dialect}查询语句来执行，不要从特定的表中查询所有列，只根据问题查询几个相关的列。请注意只使用你在schema descriptions 中看到的列名。\n=====\n 小心不要查询不存在的列。请注意哪个列位于哪个表中。必要时，请使用表名限定列名。\n=====\n 你必须使用以下格式，每项占一行：\n\n Question: Question here\n SQLQuery: SQL Query to run \n\n Only use tables listed below.\n {schema}\n\n Question: {query_str} \n SQLQuery: "

[rag.data_loader]
type = "Local" # [Local, Oss]

[rag.data_reader]
type = "SimpleDirectoryReader"
enable_multimodal = true

# embedding configurations, source support API: OpenAI,DashScope; and local model:HuggingFace
# if use API, need set OPENAI_API_KEY or DASHSCOPE_API_KEY in ENV, If HuggingFace, need set model_name
# eg.
# source = "HuggingFace"
# model_name = "bge-small-zh-v1.5"
# embed_batch_size = 10
[rag.embedding]
source = "DashScope"
embed_batch_size = 10

[rag.embedding.multi_modal]
source = "cnclip"

[rag.evaluation]
retrieval = ["mrr", "hit_rate"]
response_label = true
response = ["Faithfulness", "Answer Relevancy", "Correctness", "Semantic Similarity"]

[rag.index]
persist_path = "localdata/storage"
vector_store.type = "FAISS"

# llm configurations, source support API: OpenAI,DashScope or PAI-EAS's deployment
# eg.
# source = "PaiEas"
# name = ""
# endpoint = ""
# token = ""
[rag.llm]
source = "DashScope"
name = "qwen-turbo"

[rag.llm.function_calling_llm]
source = ""

[rag.llm.multi_modal]
enable = false
source = ""
name = ""

[rag.llm_chat_engine]
type = "SimpleChatEngine"

[rag.node_enhancement]
tree_depth = 3
max_clusters = 52
proba_threshold = 0.10

[rag.node_parser]
type = "Sentence"
chunk_size = 500
chunk_overlap = 10

[rag.oss_store]
enable = false
bucket = ""
endpoint = ""
prefix = ""

[rag.postprocessor]
reranker_type = "simple-weighted-reranker" # [simple-weighted-reranker, model-based-reranker]
reranker_model = "bge-reranker-base" # [bge-reranker-base, bge-reranker-large]
keyword_weight = 0.3
vector_weight = 0.7
similarity_threshold = 0.5
top_n = 2

[rag.query_engine]
type = "SimpleMultiModalQueryEngine"

[rag.retriever]
similarity_top_k = 3
image_similarity_top_k = 2
retrieval_mode = "hybrid" # [hybrid, embedding, keyword, router]
query_rewrite_n = 1 # set to 1 to disable query generation
need_image = true

[rag.synthesizer]
type = "SimpleSummarize"
text_qa_template = "参考内容信息如下\n---------------------\n{context_str}\n---------------------根据提供内容而非其他知识回答问题.\n问题: {query_str}\n答案: \n"
