experiment:
  # [text dataset][pai-eval]
  - name: "text_exp1"
    eval_data_path: "example_data/eval_docs_text"
    rag_setting_file: "src/pai_rag/config/evaluation/settings_eval_for_text.toml"
    eval_model_llm:
      source: "dashscope"
      model: "qwen-max"
      max_tokens: 1024
    use_pai_eval: true
  # [custom text dataset][crag]
  - name: "text_exp2"
    dataset: "crag"
    eval_data_path: "example_data/eval_docs_crag_small"
    rag_setting_file: "src/pai_rag/config/evaluation/settings_eval_for_crag_text.toml"
    eval_model_llm:
      source: "dashscope"
      model: "qwen-max"
      max_tokens: 1024
  # [multi-modal dataset]
  - name: "multi_modal_exp1"
    eval_data_path: "example_data/eval_docs_image"
    rag_setting_file: "src/pai_rag/config/evaluation/settings_eval_for_image.toml"
    eval_model_llm:
      source: "dashscope"
      model: "qwen-vl-max"
      max_tokens: 1024
    tested_multimodal_llm:
      source: "dashscope"
      model: "qwen-vl-max"
      max_tokens: 1024
  # [custom multi-modal dataset]
  - name: "multi_modal_exp2"
    qca_dataset_path: "example_data/eval_docs_image_example/multimodal_eval_dataset_zh_example.json"
    rag_setting_file: "src/pai_rag/config/evaluation/settings_eval_for_image.toml"
    eval_model_llm:
      source: "dashscope"
      model: "qwen-vl-max"
      max_tokens: 1024
    tested_multimodal_llm:
      source: "dashscope"
      model: "qwen-vl-max"
      max_tokens: 1024
